export default {
  NATIVE_DATA: 'NATIVE_DATA',
  BRIDGE_TIMEOUT_ERR: 'Timeout! Unable to get Native Data',
  DOWNLOAD_ATTACHMENTS: 'DOWNLOAD_ATTACHMENTS',
  PRINT: 'PRINT',
  PRINT_RAW: 'PRINT_RAW',
  BACK_BUTTON: 'BACK_BUTTON',
  CLOSE_APP: 'CLOSE_APP',
  COPY_TO_CLIPBOARD: 'COPY_TEXT',
  USB_DEVICE_LIST: 'USB_DEVICE_LIST',
  BLE_DEVICE_LIST: 'BLE_DEVICE_LIST',
  DEVICES_LIST: 'DEVICES_LIST',
};
