export const CSV_Import = [
  [
    'productId',
    'shortCode',
    'name',
    'description',
    'basePrice',
    'price',
    'category',
    'tag',
    'discount',
    'offerPrice',
    'stockMonitor',
    'stockQuantity',
    'unitsEnabled',
    'unit',
    'unitName',
    'counter',
    'GSTPercent',
    'GSTInc',
  ],
  [
    '(optional)(spaces not allowed)',
    '(optional)(spaces not allowed)',
    '(mandatory)',
    '(optional)',
    '(optional)',
    '(mandatory) (Required price to be in numeric)',
    '(mandatory)',
    '(optional)',
    '(optional)',
    '(optional)',
    '(optional) (true or false)',
    '(optional) (Required stock quantity in numeric)',
    '(optional) (true or false)',
    '(optional)',
    '(optional)',
    '(optional)',
    '(optional) (Required GST percentage in numeric)',
    '(optional)',
  ],
  [null, null, 'Sample name', null, null, 10, 'Check'],
];
