export const ErrorConstants = {
  NO_ITEMS: 'No items in the cart',
  OFFERPRICE: 'Offer price cannot be greater than the actual price!',
  PAYMENT_MODE: 'Select payment mode',
  ORDER_TYPE: 'Select order type',
  PRINT_MODE: 'Select print mode',
  SOMETHING_WRONG: 'Something went wrong',
  FAILED_TO_FETCH_ADDITIONAL_DISCOUNT: 'Failed to fetch additional discount',
  ADDITIOAL_DISCOUNT: 'Additional discount cannot be greater than the total order value!',
  UNABLE_CHANGE_STATUS: 'Unable to change status, Try again',
  VALID_PHONE_NUMBER: 'Enter a valid phone number',
  VALID_PRODUCT: 'Enter a valid Product',
  NAME_REQUIRED: 'Name cannot be empty',
  LABEL_REQUIRED: 'Custom label cannot be empty',
  CUSTOM_CODE_REQURIED: 'Custom code cannot be empty',
  PHONE_NUMBER_REQUIRED: 'Phone number is required',
  NUMBER_NOT_UNIQUE: 'Number already exists',
  CUSTOM_NUMBER_NOT_UNIQUE: 'Code already exists',
  PHONE_NUMBER_ALREADY_EXISTS: 'Number already exists!',
  SELECT_STORE: 'Select store',
  AFTER_SUBMIT: 'afterSubmit',
  FILE_LARGE: 'File size large!',
  VERTICAL_ASPECT: 'Select an image of vertical aspect ratio',
  FAILED_TO_UPDATE_GST: 'Failed to update GST',
  FAILED_TO_REMOVE_GST: 'Failed to remove GST',
  GST_NUMBER_IS_REQUIRED: 'GST number is required',
  GST_PERCENTAGE_IS_REQUIRED_AND_POSITIVE_NUMBER:
    'GST percentage is required and should be positive',
  CUSTOMER_NAME_IS_REQUIRED: 'Customer name is required',
  CUSTOMER_PHONE_NUMBER_REQUIRED: 'Customer phone number required',
  CUSTOMER_PHONE_NUMBER_SHOULD_BE_VALID: 'Customer phone number should be valid',
  CUSTOMER_ADDRESS_IS_REQUIRED: 'Customer address is required',
  CUSTOM_LABEL_IS_REQUIRED: 'Custom label is required',
  CUSTOM_CODE_IS_REQUIRED: 'Custom code is required',
  UNABLE_TO_UPDATE: 'Unable to update, Try again',
  UNABLE_TO_ADD: 'Unable to add, Try again',
  UNABLE_TO_DELETE: 'Unable to delete Product, Try again',
  UNABLE_TO_COPY: 'Unable to copy',
  UNABLE_TO_LOGOUT: 'Unable to logout',
  CUSTOMER: 'Add Customer',
  GST_NUMBER_LENGTH: 'Invalid GST number format',
  ADD_INFO: 'Add Additional Information',
  FAILED_TO_PAYMENT: 'Failed to payment',
  FAILED_TO_GET_ORDERS_LIST: 'Failed to get orders list',
  FAILED_TO_GET_ORDER_DETAILS: 'Failed to get order details',
  FAILED_TO_GET_PAYMENT_DETAILS: 'Failed to get payment details',
  AMOUNT_IS_REQUIRED: 'Amount is required',
  AMOUNT_IS_POSITIVE_NUMBER: 'Amount is positive number',
  FAILED_TO_SEND_EMAIL: 'Failed to send email',
  FAILED_TO_RESET_PASSWORD: 'Failed to reset password',
  FAILED_TO_DOWNLOAD_CSV: 'Failed to download csv',
  FAILED_TO_DOWNLOAD_EXCEL: 'Failed to download excel',
  FAILED_TO_DOWNLOAD_PDF: 'Failed to download pdf',
  ADD_HOLD_IS_FAILED: 'Add hold is failed',
  REMOVE_HOLD_IS_FAILED: 'Remove hold is failed',
  QUANTITY_IS_REQUIRED: 'Quantity is required',
  FAILED_TO_FETCH: 'Failed to fetch',
  NAME_IS_REQUIRED: 'Name is required',
  RATE_IS_REQUIRED: 'Rate is required',
  CREDIT_AMOUNT_IS_REQUIRED: 'Credit Amount is required',
  GST_IS_REQUIRED: 'GST is required',
  QUANTITY_PHONE_NUMBER_SHOULD_BE_VALID: 'Quantity should be valid',
  RATE_PHONE_NUMBER_SHOULD_BE_VALID: 'Rate should be valid',
  CREDIT_AMOUNT_SHOULD_BE_VALID: 'Credit amount should be valid',
  INVALID_WHATSAPP_NUMBER: 'Invalid whatsapp number',
  INVALID_AMOUNT: 'Invalid amount',
  TABLE_NAME_IS_REQUIRED: 'Table name is required',
  TABLE_CAPACITY_IS_REQUIRED: 'Table capacity is required',
  FAILED_TO_DELETE_ORDERS: 'Failed to delete orders',
  UNABLE_DELETE_INTEGRATION: 'Unable to delete Integration',
  UNABLE_MERCHANTWISE_CUSTOMER: 'Failed to Enable Merchantwise Customer',
  ERROR_BULK_CLOSE: 'Failed to enable bulk close',
  ERROR_CUSTOMER_LIST: 'Failed to fetch Customer list',
  PLEASE_FILL_ATLEAST_ONE_DAY_SLOT: 'Please fill atleast one day slot',
  SORT_ORDER_IS_REQUIRED: 'Sort order is required',
  PRICE_MUST_BE_POSITIVE_NUMBER: 'Price must be positive number',
  TRANSLATION_NAME_IS_REQUIRED: 'Translation name is required',
  LANGUAGE_IS_REQUIRED: 'Language is required',
  PRICE_IS_REQUIRED: 'Price is required',
  PRICE_SHOULD_BE_GREATER_THAN_0: 'Price should be greater than 0',
  FOOD_TYPE_IS_REQUIRED: 'Food type is required',
  AT_LEAST_ONE_OPTION_GROUP_IS_REQUIRED: 'At least one option group is required',
  OPTION_GROUP_IS_REQUIRED: 'Option group is required',
  TRANSLATION_NAME_IS_REQUIRED: 'Translation name is required',
  LANGUAGE_IS_REQUIRED: 'Language is required',
  MIN_SELECT_MUST_BE_A_NUMBER: 'Min select must be a number',
  MIN_SELECT_CANNOT_BE_LESS_THAN_0: 'Min select cannot be less than 0',
  MAX_SELECT_MUST_BE_A_NUMBER: 'Max select must be a number',
  MAX_SELECT_CANNOT_BE_LESS_THAN_1: 'Max select cannot be less than 1',
  AT_LEAST_ONE_ITEM_IS_REQUIRED: 'At least one item is required',
  ITEM_IS_REQUIRED: 'Item is required',
  ERROR_COUPON: 'Failed to validate coupon',
  ERROR_COUPON_INVALID: 'Invalid or expired coupon',
  ERROR_COUPON_CANCELED: 'Failed to cancel the transaction.',
  INVALID_TERMINAL_ID: 'Invalid terminal ID',
};

export const CatchErrorValidationConstants = {
  ALREADY_MANAGER: 'already have a manager',
};
