export const LANGUAGE_CONSTANTS = [
  {
    lang_code: 'aar',
    id: 'aa',
    _label: 'Qafaraf',
    lang_name: 'Afar',
    label: 'Afar (Qafaraf)',
  },
  {
    lang_code: 'abk',
    id: 'ab',
    _label: 'Аҧсуа',
    lang_name: 'Abkhazian',
    label: 'Abkhazian (Аҧсуа)',
  },
  {
    lang_code: 'afr',
    id: 'af',
    _label: 'Afrikaans',
    lang_name: 'Afrikaans',
    label: 'Afrikaans (Afrikaans)',
  },
  {
    lang_code: 'aka',
    id: 'ak',
    _label: 'Akan',
    lang_name: 'Akan',
    label: 'Akan (Akan)',
  },
  {
    lang_code: 'alb',
    id: 'sq',
    _label: 'Shqip',
    lang_name: 'Albanian',
    label: 'Albanian (Shqip)',
  },
  {
    lang_code: 'amh',
    id: 'am',
    _label: 'አማርኛ',
    lang_name: 'Amharic',
    label: 'Amharic (አማርኛ)',
  },
  {
    lang_code: 'ara',
    id: 'ar',
    _label: 'العربية',
    lang_name: 'Arabic',
    label: 'Arabic (العربية)',
  },
  {
    lang_code: 'arg',
    id: 'an',
    _label: 'Aragonés',
    lang_name: 'Aragonese',
    label: 'Aragonese (Aragonés)',
  },
  {
    lang_code: 'arm',
    id: 'hy',
    _label: 'Հայերեն',
    lang_name: 'Armenian',
    label: 'Armenian (Հայերեն)',
  },
  {
    lang_code: 'asm',
    id: 'as',
    _label: 'অসমীয়া',
    lang_name: 'Assamese',
    label: 'Assamese (অসমীয়া)',
  },
  {
    lang_code: 'ava',
    id: 'av',
    _label: 'Авар мацӀ',
    lang_name: 'Avaric',
    label: 'Avaric (Авар мацӀ)',
  },
  {
    lang_code: 'ave',
    id: 'ae',
    _label: 'Avesta',
    lang_name: 'Avestan',
    label: 'Avestan (Avesta)',
  },
  {
    lang_code: 'aym',
    id: 'ay',
    _label: 'Aymar aru',
    lang_name: 'Aymara',
    label: 'Aymara (Aymar aru)',
  },
  {
    lang_code: 'aze',
    id: 'az',
    _label: 'Azərbaycan dili',
    lang_name: 'Azerbaijani',
    label: 'Azerbaijani (Azərbaycan dili)',
  },
  {
    lang_code: 'bak',
    id: 'ba',
    _label: 'Башҡорт теле',
    lang_name: 'Bashkir',
    label: 'Bashkir (Башҡорт теле)',
  },
  {
    lang_code: 'bam',
    id: 'bm',
    _label: 'Bamanankan',
    lang_name: 'Bambara',
    label: 'Bambara (Bamanankan)',
  },
  {
    lang_code: 'baq',
    id: 'eu',
    _label: 'Euskara',
    lang_name: 'Basque',
    label: 'Basque (Euskara)',
  },
  {
    lang_code: 'bel',
    id: 'be',
    _label: 'Беларуская',
    lang_name: 'Belarusian',
    label: 'Belarusian (Беларуская)',
  },
  {
    lang_code: 'ben',
    id: 'bn',
    _label: 'বাংলা',
    lang_name: 'Bengali',
    label: 'Bengali (বাংলা)',
  },
  {
    lang_code: 'bih',
    id: 'bh',
    _label: 'भोजपुरी',
    lang_name: 'Bihari lang_names',
    label: 'Bihari lang_names (भोजपुरी)',
  },
  {
    lang_code: 'bis',
    id: 'bi',
    _label: 'Bislama',
    lang_name: 'Bislama',
    label: 'Bislama (Bislama)',
  },
  {
    lang_code: 'bos',
    id: 'bs',
    _label: 'Bosanski',
    lang_name: 'Bosnian',
    label: 'Bosnian (Bosanski)',
  },
  {
    lang_code: 'bre',
    id: 'br',
    _label: 'Brezhoneg',
    lang_name: 'Breton',
    label: 'Breton (Brezhoneg)',
  },
  {
    lang_code: 'bul',
    id: 'bg',
    _label: 'Български',
    lang_name: 'Bulgarian',
    label: 'Bulgarian (Български)',
  },
  {
    lang_code: 'bur',
    id: 'my',
    _label: 'Burmese',
    lang_name: 'Burmese',
    label: 'Burmese (Burmese)',
  },
  {
    lang_code: 'cat',
    id: 'ca',
    _label: 'Català',
    lang_name: 'Catalan; Valencian',
    label: 'Catalan; Valencian (Català)',
  },
  {
    lang_code: 'cha',
    id: 'ch',
    _label: 'Chamoru',
    lang_name: 'Chamorro',
    label: 'Chamorro (Chamoru)',
  },
  {
    lang_code: 'che',
    id: 'ce',
    _label: 'Нохчийн мотт',
    lang_name: 'Chechen',
    label: 'Chechen (Нохчийн мотт)',
  },
  {
    lang_code: 'chu',
    id: 'cu',
    _label: 'ѩзыкъ словѣньскъ',
    lang_name: 'Church Slavic; ',
    label: 'Church Slavic (ѩзыкъ словѣньскъ)',
  },
  {
    lang_code: 'chv',
    id: 'cv',
    _label: 'Чӑвашла',
    lang_name: 'Chuvash',
    label: 'Chuvash (Чӑвашла)',
  },
  {
    lang_code: 'cor',
    id: 'kw',
    _label: 'Kernewek',
    lang_name: 'Cornish',
    label: 'Cornish (Kernewek)',
  },
  {
    lang_code: 'cos',
    id: 'co',
    _label: 'Corsu',
    lang_name: 'Corsican',
    label: 'Corsican (Corsu)',
  },
  {
    lang_code: 'cre',
    id: 'cr',
    _label: 'Nehiyaw',
    lang_name: 'Cree',
    label: 'Cree (Nehiyaw)',
  },
  {
    lang_code: 'cze',
    id: 'cs',
    _label: 'Čeština',
    lang_name: 'Czech',
    label: 'Czech (Čeština)',
  },
  {
    lang_code: 'dan',
    id: 'da',
    _label: 'Dansk',
    lang_name: 'Danish',
    label: 'Danish (Dansk)',
  },
  {
    lang_code: 'div',
    id: 'dv',
    _label: 'ދިވެހި',
    lang_name: 'Divehi; Dhivehi; Maldivian',
    label: 'Divehi; Dhivehi; Maldivian (ދިވެހި)',
  },
  {
    lang_code: 'dut',
    id: 'nl',
    _label: 'Nederlands',
    lang_name: 'Dutch; Flemish',
    label: 'Dutch; Flemish (Nederlands)',
  },
  {
    lang_code: 'dzo',
    id: 'dz',
    _label: 'རྫོང་ཁ',
    lang_name: 'Dzongkha',
    label: 'Dzongkha (རྫོང་ཁ)',
  },
  {
    lang_code: 'eng',
    id: 'en',
    _label: 'English',
    lang_name: 'English',
    label: 'English (English)',
  },
  {
    lang_code: 'epo',
    id: 'eo',
    _label: 'Esperanto',
    lang_name: 'Esperanto',
    label: 'Esperanto (Esperanto)',
  },
  {
    lang_code: 'est',
    id: 'et',
    _label: 'Eesti',
    lang_name: 'Estonian',
    label: 'Estonian (Eesti)',
  },
  {
    lang_code: 'ewe',
    id: 'ee',
    _label: 'Ewe',
    lang_name: 'Ewe',
    label: 'Ewe (Ewe)',
  },
  {
    lang_code: 'fao',
    id: 'fo',
    _label: 'Føroyskt',
    lang_name: 'Faroese',
    label: 'Faroese (Føroyskt)',
  },
  {
    lang_code: 'fij',
    id: 'fj',
    _label: 'Na Vosa Vakaviti',
    lang_name: 'Fijian',
    label: 'Fijian (Na Vosa Vakaviti)',
  },
  {
    lang_code: 'fin',
    id: 'fi',
    _label: 'Suomi',
    lang_name: 'Finnish',
    label: 'Finnish (Suomi)',
  },
  {
    lang_code: 'fre',
    id: 'fr',
    _label: 'Français',
    lang_name: 'French',
    label: 'French (Français)',
  },
  {
    lang_code: 'fry',
    id: 'fy',
    _label: 'Frysk',
    lang_name: 'Western Frisian',
    label: 'Western Frisian (Frysk)',
  },
  {
    lang_code: 'ful',
    id: 'ff',
    _label: 'Fulfulde',
    lang_name: 'Fulah',
    label: 'Fulah (Fulfulde)',
  },
  {
    lang_code: 'geo',
    id: 'ka',
    _label: 'ქართული',
    lang_name: 'Georgian',
    label: 'Georgian (ქართული)',
  },
  {
    lang_code: 'ger',
    id: 'de',
    _label: 'Deutsch',
    lang_name: 'German',
    label: 'German (Deutsch)',
  },
  {
    lang_code: 'gla',
    id: 'gd',
    _label: 'Gàidhlig',
    lang_name: 'Gaelic; Scottish Gaelic',
    label: 'Gaelic; Scottish Gaelic (Gàidhlig)',
  },
  {
    lang_code: 'gle',
    id: 'ga',
    _label: 'Gaeilge',
    lang_name: 'Irish',
    label: 'Irish (Gaeilge)',
  },
  {
    lang_code: 'glg',
    id: 'gl',
    _label: 'Galego',
    lang_name: 'Galician',
    label: 'Galician (Galego)',
  },
  {
    lang_code: 'glv',
    id: 'gv',
    _label: 'Gaelg',
    lang_name: 'Manx',
    label: 'Manx (Gaelg)',
  },
  {
    lang_code: 'gre',
    id: 'el',
    _label: 'Ελληνικά',
    lang_name: 'Greek, Modern  (1453 ())',
    label: 'Greek, Modern  (1453 () (Ελληνικά)',
  },
  {
    lang_code: 'grn',
    id: 'gn',
    _label: "Avañe'ẽ",
    lang_name: 'Guarani',
    label: "Guarani (Avañe'ẽ)",
  },
  {
    lang_code: 'guj',
    id: 'gu',
    _label: 'ગુજરાતી',
    lang_name: 'Gujarati',
    label: 'Gujarati (ગુજરાતી)',
  },
  {
    lang_code: 'hat',
    id: 'ht',
    _label: 'Kreyòl Ayisyen',
    lang_name: 'Haitian; Haitian Creole',
    label: 'Haitian; Haitian Creole (Kreyòl Ayisyen)',
  },
  {
    lang_code: 'hau',
    id: 'ha',
    _label: 'Hausa',
    lang_name: 'Hausa',
    label: 'Hausa (Hausa)',
  },
  {
    lang_code: 'heb',
    id: 'he',
    _label: 'עברית',
    lang_name: 'Hebrew',
    label: 'Hebrew (עברית)',
  },
  {
    lang_code: 'her',
    id: 'hz',
    _label: 'Otjiherero',
    lang_name: 'Herero',
    label: 'Herero (Otjiherero)',
  },
  {
    lang_code: 'hin',
    id: 'hi',
    _label: 'हिन्दी',
    lang_name: 'Hindi',
    label: 'Hindi (हिन्दी)',
  },
  {
    lang_code: 'hmo',
    id: 'ho',
    _label: 'Hiri Motu',
    lang_name: 'Hiri Motu',
    label: 'Hiri Motu (Hiri Motu)',
  },
  {
    lang_code: 'hrv',
    id: 'hr',
    _label: 'Hrvatski',
    lang_name: 'Croatian',
    label: 'Croatian (Hrvatski)',
  },
  {
    lang_code: 'hun',
    id: 'hu',
    _label: 'Magyar',
    lang_name: 'Hungarian',
    label: 'Hungarian (Magyar)',
  },
  {
    lang_code: 'ibo',
    id: 'ig',
    _label: 'Igbo',
    lang_name: 'Igbo',
    label: 'Igbo (Igbo)',
  },
  {
    lang_code: 'ice',
    id: 'is',
    _label: 'Íslenska',
    lang_name: 'Icelandic',
    label: 'Icelandic (Íslenska)',
  },
  {
    lang_code: 'ido',
    id: 'io',
    _label: 'Ido',
    lang_name: 'Ido',
    label: 'Ido (Ido)',
  },
  {
    lang_code: 'iii',
    id: 'ii',
    _label: 'ꆈꌠ꒿',
    lang_name: 'Sichuan Yi; Nuosu',
    label: 'Sichuan Yi; Nuosu (ꆈꌠ꒿)',
  },
  {
    lang_code: 'iku',
    id: 'iu',
    _label: 'ᐃᓄᒃᑎᑐᑦ',
    lang_name: 'Inuktitut',
    label: 'Inuktitut (ᐃᓄᒃᑎᑐᑦ)',
  },
  {
    lang_code: 'ile',
    id: 'ie',
    _label: 'Interlingue',
    lang_name: 'Interlingue; Occidental',
    label: 'Interlingue; Occidental (Interlingue)',
  },
  {
    lang_code: 'ina',
    id: 'ia',
    _label: 'Interlingua',
    lang_name: 'Interlingua ',
    label: 'Interlingua ',
  },
  {
    lang_code: 'ind',
    id: 'id',
    _label: 'Bahasa Indonesia',
    lang_name: 'Indonesian',
    label: 'Indonesian (Bahasa Indonesia)',
  },
  {
    lang_code: 'ipk',
    id: 'ik',
    _label: 'Iñupiatun',
    lang_name: 'Inupiaq',
    label: 'Inupiaq (Iñupiatun)',
  },
  {
    lang_code: 'ita',
    id: 'it',
    _label: 'Italiano',
    lang_name: 'Italian',
    label: 'Italian (Italiano)',
  },
  {
    lang_code: 'jav',
    id: 'jv',
    _label: 'ꦧꦱꦗꦮ',
    lang_name: 'Javanese',
    label: 'Javanese (ꦧꦱꦗꦮ)',
  },
  {
    lang_code: 'jpn',
    id: 'ja',
    _label: '日本語',
    lang_name: 'Japanese',
    label: 'Japanese (日本語)',
  },
  {
    lang_code: 'kal',
    id: 'kal',
    _label: 'Kalaallisut; Greenlandic ',
    lang_name: 'Kalaallisut; Greenlandic',
    label: 'Kalaallisut; Greenlandic ',
  },
  {
    lang_code: 'kan',
    id: 'kn',
    _label: 'ಕನ್ನಡ',
    lang_name: 'Kannada',
    label: 'Kannada (ಕನ್ನಡ)',
  },
  {
    lang_code: 'kas',
    id: 'ks',
    _label: 'کٲشُر',
    lang_name: 'Kashmiri',
    label: 'Kashmiri (کٲشُر)',
  },
  {
    lang_code: 'kau',
    id: 'kau',
    _label: 'Kanuri ',
    lang_name: 'Kanuri',
    label: 'Kanuri ',
  },
  {
    lang_code: 'kaz',
    id: 'kk',
    _label: 'Қазақ тілі',
    lang_name: 'Kazakh',
    label: 'Kazakh (Қазақ тілі)',
  },
  {
    lang_code: 'khm',
    id: 'km',
    _label: 'ភាសាខ្មែរ',
    lang_name: 'Central Khmer',
    label: 'Central Khmer (ភាសាខ្មែរ)',
  },
  {
    lang_code: 'kik',
    id: 'kik',
    lang_name: 'Kikuyu; Gikuyu',
    _label: 'Kikuyu; Gikuyu ',
    label: 'Kikuyu; Gikuyu ',
  },
  {
    lang_code: 'kin',
    id: 'kin',
    lang_name: 'Kinyarwanda',
    label: 'Kinyarwanda ',
    _label: 'Kinyarwanda ',
  },
  {
    lang_code: 'kir',
    id: 'ky',
    _label: 'Кыргыз тили',
    lang_name: 'Kirghiz; Kyrgyz',
    label: 'Kirghiz; Kyrgyz (Кыргыз тили)',
  },
  {
    lang_code: 'kom',
    id: 'kv',
    _label: 'Коми кыв',
    lang_name: 'Komi',
    label: 'Komi (Коми кыв)',
  },
  {
    lang_code: 'kon',
    id: 'kg',
    _label: 'Kikongo',
    lang_name: 'Kongo',
    label: 'Kongo (Kikongo)',
  },
  {
    lang_code: 'kor',
    id: 'ko',
    _label: '한국어',
    lang_name: 'Korean',
    label: 'Korean (한국어)',
  },
  {
    lang_code: 'kua',
    id: 'kua',
    lang_name: 'Kuanyama; Kwanyama',
    label: 'Kuanyama; Kwanyama ',
    _label: 'Kuanyama; Kwanyama ',
  },
  {
    lang_code: 'kur',
    id: 'ku',
    _label: 'Kurdî',
    lang_name: 'Kurdish',
    label: 'Kurdish (Kurdî)',
  },
  {
    lang_code: 'lao',
    id: 'lo',
    _label: 'ພາສາລາວ',
    lang_name: 'Lao',
    label: 'Lao (ພາສາລາວ)',
  },
  {
    lang_code: 'lat',
    id: 'la',
    _label: 'Lingua Latina',
    lang_name: 'Latin',
    label: 'Latin (Lingua Latina)',
  },
  {
    lang_code: 'lav',
    id: 'lv',
    _label: 'Latviešu valoda',
    lang_name: 'Latvian',
    label: 'Latvian (Latviešu valoda)',
  },
  {
    lang_code: 'lim',
    id: 'li',
    _label: 'Limburgs',
    lang_name: 'Limburgan; Limburger; Limburgish',
    label: 'Limburgan; Limburger; Limburgish (Limburgs)',
  },
  {
    lang_code: 'lin',
    id: 'ln',
    _label: 'Lingála',
    lang_name: 'Lingala',
    label: 'Lingala (Lingála)',
  },
  {
    lang_code: 'lit',
    id: 'lt',
    _label: 'Lietuvių kalba',
    lang_name: 'Lithuanian',
    label: 'Lithuanian (Lietuvių kalba)',
  },
  {
    lang_code: 'ltz',
    id: 'lb',
    _label: 'Lëtzebuergesch',
    lang_name: 'Luxembourgish; Letzeburgesch',
    label: 'Luxembourgish; Letzeburgesch (Lëtzebuergesch)',
  },
  {
    lang_code: 'lub',
    id: 'lu',
    _label: 'Tshiluba',
    lang_name: 'Luba (Katanga)',
    label: 'Luba (Katanga (Tshiluba)',
  },
  {
    lang_code: 'lug',
    id: 'lug',
    lang_name: 'Ganda',
    label: 'Ganda',
    _label: 'Ganda',
  },
  {
    lang_code: 'mac',
    id: 'mk',
    _label: 'Македонски',
    lang_name: 'Macedonian',
    label: 'Macedonian (Македонски)',
  },
  {
    lang_code: 'mah',
    id: 'mah',
    lang_name: 'Marshallese',
    label: 'Marshallese',
    _label: 'Marshallese',
  },
  {
    lang_code: 'mal',
    id: 'ml',
    _label: 'മലയാളം',
    lang_name: 'Malayalam',
    label: 'Malayalam (മലയാളം)',
  },
  {
    lang_code: 'mao',
    id: 'mi',
    _label: 'Māori',
    lang_name: 'Maori',
    label: 'Maori (Māori)',
  },
  {
    lang_code: 'mar',
    id: 'mr',
    _label: 'मराठी',
    lang_name: 'Marathi',
    label: 'Marathi (मराठी)',
  },
  {
    lang_code: 'may',
    id: 'ms',
    _label: 'Bahasa Melayu',
    lang_name: 'Malay',
    label: 'Malay (Bahasa Melayu)',
  },
  {
    lang_code: 'mlg',
    id: 'mg',
    _label: 'Malagasy',
    lang_name: 'Malagasy',
    label: 'Malagasy (Malagasy)',
  },
  {
    lang_code: 'mlt',
    id: 'mt',
    _label: 'Malti',
    lang_name: 'Maltese',
    label: 'Maltese (Malti)',
  },
  {
    lang_code: 'mon',
    id: 'mn',
    _label: 'Монгол хэл',
    lang_name: 'Mongolian',
    label: 'Mongolian (Монгол хэл)',
  },
  {
    lang_code: 'nau',
    id: 'na',
    _label: 'Dorerin Naoero',
    lang_name: 'Nauru',
    label: 'Nauru (Dorerin Naoero)',
  },
  {
    lang_code: 'nav',
    id: 'nv',
    _label: 'Diné bizaad',
    lang_name: 'Navajo; Navaho',
    label: 'Navajo; Navaho (Diné bizaad)',
  },
  {
    lang_code: 'nbl',
    id: 'nr',
    _label: 'isiNdebele',
    lang_name: 'Ndebele, South; South Ndebele',
    label: 'Ndebele, South; South Ndebele (isiNdebele)',
  },
  {
    lang_code: 'nde',
    id: 'nd',
    _label: 'isiNdebele',
    lang_name: 'Ndebele, North; North Ndebele',
    label: 'Ndebele, North; North Ndebele (isiNdebele)',
  },
  {
    lang_code: 'ndo',
    id: 'ng',
    _label: 'Oshiwambo',
    lang_name: 'Ndonga',
    label: 'Ndonga (Oshiwambo)',
  },
  {
    lang_code: 'nep',
    id: 'ne',
    _label: 'नेपाली',
    lang_name: 'Nepali',
    label: 'Nepali (नेपाली)',
  },
  {
    lang_code: 'nno',
    id: 'nn',
    _label: 'Norsk nynorsk',
    lang_name: 'Norwegian Nynorsk; Nynorsk, Norwegian',
    label: 'Norwegian Nynorsk; Nynorsk, Norwegian (Norsk nynorsk)',
  },
  {
    lang_code: 'nob',
    id: 'nb',
    _label: 'Norsk bokmål',
    lang_name: 'Bokmål, Norwegian; Norwegian Bokmål',
    label: 'Bokmål, Norwegian; Norwegian Bokmål (Norsk bokmål)',
  },
  {
    lang_code: 'nor',
    id: 'no',
    _label: 'Norsk',
    lang_name: 'Norwegian',
    label: 'Norwegian (Norsk)',
  },
  {
    lang_code: 'nya',
    id: 'ny',
    _label: 'Chi (Chewa)',
    lang_name: 'Chichewa; Chewa; Nyanja',
    label: 'Chichewa; Chewa; Nyanja (Chi (Chewa)',
  },
  {
    lang_code: 'oci',
    id: 'oc',
    _label: 'Occitan',
    lang_name: 'Occitan  (post 1500); Provençal',
    label: 'Occitan  (post 1500); Provençal (Occitan)',
  },
  {
    lang_code: 'oji',
    id: 'oj',
    _label: 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
    lang_name: 'Ojibwa',
    label: 'Ojibwa (ᐊᓂᔑᓈᐯᒧᐎᓐ)',
  },
  {
    lang_code: 'ori',
    id: 'or',
    _label: 'ଓଡ଼ିଆ',
    lang_name: 'Oriya',
    label: 'Oriya (ଓଡ଼ିଆ)',
  },
  {
    lang_code: 'orm',
    id: 'om',
    _label: 'Afaan Oromoo',
    lang_name: 'Oromo',
    label: 'Oromo (Afaan Oromoo)',
  },
  {
    lang_code: 'oss',
    id: 'os',
    _label: 'Ирон æвзаг',
    lang_name: 'Ossetian; Ossetic',
    label: 'Ossetian; Ossetic (Ирон æвзаг)',
  },
  {
    lang_code: 'pan',
    id: 'pa',
    _label: 'ਪੰਜਾਬੀ',
    lang_name: 'Panjabi; Punjabi',
    label: 'Panjabi; Punjabi (ਪੰਜਾਬੀ)',
  },
  {
    lang_code: 'per',
    id: 'per',
    lang_name: 'Persian',
    label: 'Persian ',
    _label: 'Persian ',
  },
  {
    lang_code: 'pli',
    id: 'pi',
    _label: 'पालि',
    lang_name: 'Pali',
    label: 'Pali (पालि)',
  },
  {
    lang_code: 'pol',
    id: 'pl',
    _label: 'Polski',
    lang_name: 'Polish',
    label: 'Polish (Polski)',
  },
  {
    lang_code: 'por',
    id: 'pt',
    _label: 'Português',
    lang_name: 'Portuguese',
    label: 'Portuguese (Português)',
  },
  {
    lang_code: 'pus',
    id: 'ps',
    _label: 'پښتو',
    lang_name: 'Pushto; Pashto',
    label: 'Pushto; Pashto (پښتو)',
  },
  {
    lang_code: 'que',
    id: 'qu',
    _label: 'Runa Simi',
    lang_name: 'Quechua',
    label: 'Quechua (Runa Simi)',
  },
  {
    lang_code: 'roh',
    id: 'rm',
    _label: 'Rumantsch',
    lang_name: 'Romansh',
    label: 'Romansh (Rumantsch)',
  },
  {
    lang_code: 'rum',
    id: 'rum',
    lang_name: 'Romanian; Moldavian; Moldovan',
    label: 'Romanian; Moldavian; Moldovan ',
    _label: 'Romanian; Moldavian; Moldovan ',
  },
  {
    lang_code: 'run',
    id: 'rn',
    _label: 'Ikirundi',
    lang_name: 'Rundi',
    label: 'Rundi (Ikirundi)',
  },
  {
    lang_code: 'rus',
    id: 'ru',
    _label: 'Русский',
    lang_name: 'Russian',
    label: 'Russian (Русский)',
  },
  {
    lang_code: 'sag',
    id: 'sg',
    _label: 'Sängö',
    lang_name: 'Sango',
    label: 'Sango (Sängö)',
  },
  {
    lang_code: 'san',
    id: 'sa',
    _label: 'संस्कृतम्',
    lang_name: 'Sanskrit',
    label: 'Sanskrit (संस्कृतम्)',
  },
  {
    lang_code: 'sin',
    id: 'si',
    _label: 'සිංහල',
    lang_name: 'Sinhala; Sinhalese',
    label: 'Sinhala; Sinhalese (සිංහල)',
  },
  {
    lang_code: 'slo',
    id: 'sk',
    _label: 'Slovenčina',
    lang_name: 'Slovak',
    label: 'Slovak (Slovenčina)',
  },
  {
    lang_code: 'slv',
    id: 'sl',
    _label: 'Slovenščina',
    lang_name: 'Slovenian',
    label: 'Slovenian (Slovenščina)',
  },
  {
    lang_code: 'sme',
    id: 'se',
    _label: 'Sámegiella',
    lang_name: 'Northern Sami',
    label: 'Northern Sami (Sámegiella)',
  },
  {
    lang_code: 'smo',
    id: 'sm',
    _label: 'Gagana Samoa',
    lang_name: 'Samoan',
    label: 'Samoan (Gagana Samoa)',
  },
  {
    lang_code: 'sna',
    id: 'sn',
    _label: 'chiShona',
    lang_name: 'Shona',
    label: 'Shona (chiShona)',
  },
  {
    lang_code: 'snd',
    id: 'sd',
    _label: 'سنڌي',
    lang_name: 'Sindhi',
    label: 'Sindhi (سنڌي)',
  },
  {
    lang_code: 'som',
    id: 'so',
    _label: 'Af (Soomaali)',
    lang_name: 'Somali',
    label: 'Somali (Af (Soomaali)',
  },
  {
    lang_code: 'sot',
    id: 'st',
    _label: 'Sesotho',
    lang_name: 'Sotho, Southern',
    label: 'Sotho, Southern (Sesotho)',
  },
  {
    lang_code: 'spa',
    id: 'es',
    _label: 'Español',
    lang_name: 'Spanish; Castilian',
    label: 'Spanish; Castilian (Español)',
  },
  {
    lang_code: 'srd',
    id: 'sc',
    _label: 'Sardu',
    lang_name: 'Sardinian',
    label: 'Sardinian (Sardu)',
  },
  {
    lang_code: 'srp',
    id: 'sr',
    _label: 'Српски',
    lang_name: 'Serbian',
    label: 'Serbian (Српски)',
  },
  {
    lang_code: 'ssw',
    id: 'ss',
    _label: 'SiSwati',
    lang_name: 'Swati',
    label: 'Swati (SiSwati)',
  },
  {
    lang_code: 'sun',
    id: 'su',
    _label: 'Basa Sunda',
    lang_name: 'Sundanese',
    label: 'Sundanese (Basa Sunda)',
  },
  {
    lang_code: 'swa',
    id: 'sw',
    _label: 'Kiswahili',
    lang_name: 'Swahili',
    label: 'Swahili (Kiswahili)',
  },
  {
    lang_code: 'swe',
    id: 'sv',
    _label: 'Svenska',
    lang_name: 'Swedish',
    label: 'Swedish (Svenska)',
  },
  {
    lang_code: 'tah',
    id: 'ty',
    _label: 'Reo Tahiti',
    lang_name: 'Tahitian',
    label: 'Tahitian (Reo Tahiti)',
  },
  {
    lang_code: 'tam',
    id: 'ta',
    _label: 'தமிழ்',
    lang_name: 'Tamil',
    label: 'Tamil (தமிழ்)',
  },
  {
    lang_code: 'tat',
    id: 'tt',
    _label: 'Татар теле',
    lang_name: 'Tatar',
    label: 'Tatar (Татар теле)',
  },
  {
    lang_code: 'tel',
    id: 'te',
    _label: 'తెలుగు',
    lang_name: 'Telugu',
    label: 'Telugu (తెలుగు)',
  },
  {
    lang_code: 'tgk',
    id: 'tg',
    _label: 'Тоҷикӣ',
    lang_name: 'Tajik',
    label: 'Tajik (Тоҷикӣ)',
  },
  {
    lang_code: 'tgl',
    id: 'tl',
    _label: 'Tagalog',
    lang_name: 'Tagalog',
    label: 'Tagalog (Tagalog)',
  },
  {
    lang_code: 'tha',
    id: 'th',
    _label: 'ไทย',
    lang_name: 'Thai',
    label: 'Thai (ไทย)',
  },
  {
    lang_code: 'tib',
    id: 'bo',
    _label: 'བོད་ཡིག',
    lang_name: 'Tibetan',
    label: 'Tibetan (བོད་ཡིག)',
  },
  {
    lang_code: 'tir',
    id: 'ti',
    _label: 'ትግርኛ',
    lang_name: 'Tigrinya',
    label: 'Tigrinya (ትግርኛ)',
  },
  {
    lang_code: 'ton',
    id: 'to',
    _label: 'Lea faka (Tonga)',
    lang_name: 'Tonga  (Tonga Islands)',
    label: 'Tonga  (Tonga Islands) (Lea faka (Tonga)',
  },
  {
    lang_code: 'tsn',
    id: 'tsn',
    lang_name: 'Tswana',
    label: 'Tswana ',
    _label: 'Tswana ',
  },
  {
    lang_code: 'tso',
    id: 'ts',
    _label: 'Xitsonga',
    lang_name: 'Tsonga',
    label: 'Tsonga (Xitsonga)',
  },
  {
    lang_code: 'tuk',
    id: 'tk',
    _label: 'Türkmen',
    lang_name: 'Turkmen',
    label: 'Turkmen (Türkmen)',
  },
  {
    lang_code: 'tur',
    id: 'tr',
    _label: 'Türkçe',
    lang_name: 'Turkish',
    label: 'Turkish (Türkçe)',
  },
  {
    lang_code: 'twi',
    id: 'tw',
    _label: 'Twi',
    lang_name: 'Twi',
    label: 'Twi (Twi)',
  },
  {
    lang_code: 'uig',
    id: 'ug',
    _label: 'Uyƣurqə',
    lang_name: 'Uighur; Uyghur',
    label: 'Uighur; Uyghur (Uyƣurqə)',
  },
  {
    lang_code: 'ukr',
    id: 'uk',
    _label: 'Українська',
    lang_name: 'Ukrainian',
    label: 'Ukrainian (Українська)',
  },
  {
    lang_code: 'urd',
    id: 'ur',
    _label: 'اُردُو',
    lang_name: 'Urdu',
    label: 'Urdu (اُردُو)',
  },
  {
    lang_code: 'uzb',
    id: 'uz',
    _label: 'Uzbek',
    lang_name: 'Uzbek',
    label: 'Uzbek (Uzbek)',
  },
  {
    lang_code: 'ven',
    id: 've',
    _label: 'Tshivenda',
    lang_name: 'Venda',
    label: 'Venda (Tshivenda)',
  },
  {
    lang_code: 'vie',
    id: 'vi',
    _label: 'Tiếng Việt',
    lang_name: 'Vietnamese',
    label: 'Vietnamese (Tiếng Việt)',
  },
  {
    lang_code: 'vol',
    id: 'vo',
    _label: 'Volapük',
    lang_name: 'Volapük',
    label: 'Volapük (Volapük)',
  },
  {
    lang_code: 'wel',
    id: 'cy',
    _label: 'Cymraeg',
    lang_name: 'Welsh',
    label: 'Welsh (Cymraeg)',
  },
  {
    lang_code: 'wln',
    id: 'wa',
    _label: 'Walon',
    lang_name: 'Walloon',
    label: 'Walloon (Walon)',
  },
  {
    lang_code: 'wol',
    id: 'wo',
    _label: 'Wolof',
    lang_name: 'Wolof',
    label: 'Wolof (Wolof)',
  },
  {
    lang_code: 'xho',
    id: 'xh',
    _label: 'isiXhosa',
    lang_name: 'Xhosa',
    label: 'Xhosa (isiXhosa)',
  },
  {
    lang_code: 'yid',
    id: 'yi',
    _label: 'ייִדיש',
    lang_name: 'Yiddish',
    label: 'Yiddish (ייִדיש)',
  },
  {
    lang_code: 'yor',
    id: 'yo',
    _label: 'Èdè Yorùbá',
    lang_name: 'Yoruba',
    label: 'Yoruba (Èdè Yorùbá)',
  },
  {
    lang_code: 'zha',
    id: 'za',
    _label: 'Zhuang/Chuang',
    lang_name: 'Zhuang; Chuang',
    label: 'Zhuang; Chuang (Zhuang/Chuang)',
  },
  {
    lang_code: 'zul',
    id: 'zu',
    _label: 'isiZulu',
    lang_name: 'Zulu',
    label: 'Zulu (isiZulu)',
  },
];
export const DefaultAliasLanguage = {
  lang_code: 'eng',
  id: 'en',
  _label: 'English',
  lang_name: 'English',
  label: 'English (English)',
};
export const Language_labels = {
  aa: 'Afar (Qafaraf)',
  ab: 'Abkhazian (Аҧсуа)',
  af: 'Afrikaans (Afrikaans)',
  ak: 'Akan (Akan)',
  sq: 'Albanian (Shqip)',
  am: 'Amharic (አማርኛ)',
  ar: 'Arabic (العربية)',
  an: 'Aragonese (Aragonés)',
  hy: 'Armenian (Հայերեն)',
  as: 'Assamese (অসমীয়া)',
  av: 'Avaric (Авар мацӀ)',
  ae: 'Avestan (Avesta)',
  ay: 'Aymara (Aymar aru)',
  az: 'Azerbaijani (Azərbaycan dili)',
  ba: 'Bashkir (Башҡорт теле)',
  bm: 'Bambara (Bamanankan)',
  eu: 'Basque (Euskara)',
  be: 'Belarusian (Беларуская)',
  bn: 'Bengali (বাংলা)',
  bh: 'Bihari lang_names (भोजपुरी)',
  bi: 'Bislama (Bislama)',
  bs: 'Bosnian (Bosanski)',
  br: 'Breton (Brezhoneg)',
  bg: 'Bulgarian (Български)',
  my: 'Burmese (Burmese)',
  ca: 'Catalan; Valencian (Català)',
  ch: 'Chamorro (Chamoru)',
  ce: 'Chechen (Нохчийн мотт)',
  cu: 'Church Slavic (ѩзыкъ словѣньскъ)',
  cv: 'Chuvash (Чӑвашла)',
  kw: 'Cornish (Kernewek)',
  co: 'Corsican (Corsu)',
  cr: 'Cree (Nehiyaw)',
  cs: 'Czech (Čeština)',
  da: 'Danish (Dansk)',
  dv: 'Divehi; Dhivehi; Maldivian (ދިވެހި)',
  nl: 'Dutch; Flemish (Nederlands)',
  dz: 'Dzongkha (རྫོང་ཁ)',
  en: 'English (English)',
  eo: 'Esperanto (Esperanto)',
  et: 'Estonian (Eesti)',
  ee: 'Ewe (Ewe)',
  fo: 'Faroese (Føroyskt)',
  fj: 'Fijian (Na Vosa Vakaviti)',
  fi: 'Finnish (Suomi)',
  fr: 'French (Français)',
  fy: 'Western Frisian (Frysk)',
  ff: 'Fulah (Fulfulde)',
  ka: 'Georgian (ქართული)',
  de: 'German (Deutsch)',
  gd: 'Gaelic; Scottish Gaelic (Gàidhlig)',
  ga: 'Irish (Gaeilge)',
  gl: 'Galician (Galego)',
  gv: 'Manx (Gaelg)',
  el: 'Greek, Modern  (1453 () (Ελληνικά)',
  gn: "Guarani (Avañe'ẽ)",
  gu: 'Gujarati (ગુજરાતી)',
  ht: 'Haitian; Haitian Creole (Kreyòl Ayisyen)',
  ha: 'Hausa (Hausa)',
  he: 'Hebrew (עברית)',
  hz: 'Herero (Otjiherero)',
  hi: 'Hindi (हिन्दी)',
  ho: 'Hiri Motu (Hiri Motu)',
  hr: 'Croatian (Hrvatski)',
  hu: 'Hungarian (Magyar)',
  ig: 'Igbo (Igbo)',
  is: 'Icelandic (Íslenska)',
  io: 'Ido (Ido)',
  ii: 'Sichuan Yi; Nuosu (ꆈꌠ꒿)',
  iu: 'Inuktitut (ᐃᓄᒃᑎᑐᑦ)',
  ie: 'Interlingue; Occidental (Interlingue)',
  ia: 'Interlingua ',
  id: 'Indonesian (Bahasa Indonesia)',
  ik: 'Inupiaq (Iñupiatun)',
  it: 'Italian (Italiano)',
  jv: 'Javanese (ꦧꦱꦗꦮ)',
  ja: 'Japanese (日本語)',
  kal: 'Kalaallisut; Greenlandic ',
  kn: 'Kannada (ಕನ್ನಡ)',
  ks: 'Kashmiri (کٲشُر)',
  kau: 'Kanuri ',
  kk: 'Kazakh (Қазақ тілі)',
  km: 'Central Khmer (ភាសាខ្មែរ)',
  kik: 'Kikuyu; Gikuyu ',
  kin: 'Kinyarwanda ',
  ky: 'Kirghiz; Kyrgyz (Кыргыз тили)',
  kv: 'Komi (Коми кыв)',
  kg: 'Kongo (Kikongo)',
  ko: 'Korean (한국어)',
  kua: 'Kuanyama; Kwanyama ',
  ku: 'Kurdish (Kurdî)',
  lo: 'Lao (ພາສາລາວ)',
  la: 'Latin (Lingua Latina)',
  lv: 'Latvian (Latviešu valoda)',
  li: 'Limburgan; Limburger; Limburgish (Limburgs)',
  ln: 'Lingala (Lingála)',
  lt: 'Lithuanian (Lietuvių kalba)',
  lb: 'Luxembourgish; Letzeburgesch (Lëtzebuergesch)',
  lu: 'Luba (Katanga (Tshiluba)',
  lug: 'Ganda',
  mk: 'Macedonian (Македонски)',
  mah: 'Marshallese',
  ml: 'Malayalam (മലയാളം)',
  mi: 'Maori (Māori)',
  mr: 'Marathi (मराठी)',
  ms: 'Malay (Bahasa Melayu)',
  mg: 'Malagasy (Malagasy)',
  mt: 'Maltese (Malti)',
  mn: 'Mongolian (Монгол хэл)',
  na: 'Nauru (Dorerin Naoero)',
  nv: 'Navajo; Navaho (Diné bizaad)',
  nr: 'Ndebele, South; South Ndebele (isiNdebele)',
  nd: 'Ndebele, North; North Ndebele (isiNdebele)',
  ng: 'Ndonga (Oshiwambo)',
  ne: 'Nepali (नेपाली)',
  nn: 'Norwegian Nynorsk; Nynorsk, Norwegian (Norsk nynorsk)',
  nb: 'Bokmål, Norwegian; Norwegian Bokmål (Norsk bokmål)',
  no: 'Norwegian (Norsk)',
  ny: 'Chichewa; Chewa; Nyanja (Chi (Chewa)',
  oc: 'Occitan  (post 1500); Provençal (Occitan)',
  oj: 'Ojibwa (ᐊᓂᔑᓈᐯᒧᐎᓐ)',
  or: 'Oriya (ଓଡ଼ିଆ)',
  om: 'Oromo (Afaan Oromoo)',
  os: 'Ossetian; Ossetic (Ирон æвзаг)',
  pa: 'Panjabi; Punjabi (ਪੰਜਾਬੀ)',
  per: 'Persian ',
  pi: 'Pali (पालि)',
  pl: 'Polish (Polski)',
  pt: 'Portuguese (Português)',
  ps: 'Pushto; Pashto (پښتو)',
  qu: 'Quechua (Runa Simi)',
  rm: 'Romansh (Rumantsch)',
  rum: 'Romanian; Moldavian; Moldovan ',
  rn: 'Rundi (Ikirundi)',
  ru: 'Russian (Русский)',
  sg: 'Sango (Sängö)',
  sa: 'Sanskrit (संस्कृतम्)',
  si: 'Sinhala; Sinhalese (සිංහල)',
  sk: 'Slovak (Slovenčina)',
  sl: 'Slovenian (Slovenščina)',
  se: 'Northern Sami (Sámegiella)',
  sm: 'Samoan (Gagana Samoa)',
  sn: 'Shona (chiShona)',
  sd: 'Sindhi (سنڌي)',
  so: 'Somali (Af (Soomaali)',
  st: 'Sotho, Southern (Sesotho)',
  es: 'Spanish; Castilian (Español)',
  sc: 'Sardinian (Sardu)',
  sr: 'Serbian (Српски)',
  ss: 'Swati (SiSwati)',
  su: 'Sundanese (Basa Sunda)',
  sw: 'Swahili (Kiswahili)',
  sv: 'Swedish (Svenska)',
  ty: 'Tahitian (Reo Tahiti)',
  ta: 'Tamil (தமிழ்)',
  tt: 'Tatar (Татар теле)',
  te: 'Telugu (తెలుగు)',
  tg: 'Tajik (Тоҷикӣ)',
  tl: 'Tagalog (Tagalog)',
  th: 'Thai (ไทย)',
  bo: 'Tibetan (བོད་ཡིག)',
  ti: 'Tigrinya (ትግርኛ)',
  to: 'Tonga  (Tonga Islands) (Lea faka (Tonga)',
  tsn: 'Tswana ',
  ts: 'Tsonga (Xitsonga)',
  tk: 'Turkmen (Türkmen)',
  tr: 'Turkish (Türkçe)',
  tw: 'Twi (Twi)',
  ug: 'Uighur; Uyghur (Uyƣurqə)',
  uk: 'Ukrainian (Українська)',
  ur: 'Urdu (اُردُو)',
  uz: 'Uzbek (Uzbek)',
  ve: 'Venda (Tshivenda)',
  vi: 'Vietnamese (Tiếng Việt)',
  vo: 'Volapük (Volapük)',
  cy: 'Welsh (Cymraeg)',
  wa: 'Walloon (Walon)',
  wo: 'Wolof (Wolof)',
  xh: 'Xhosa (isiXhosa)',
  yi: 'Yiddish (ייִדיש)',
  yo: 'Yoruba (Èdè Yorùbá)',
  za: 'Zhuang; Chuang (Zhuang/Chuang)',
  zu: 'Zulu (isiZulu)',
};
