export const ROLE_STORAGE = {
  ROLE: 'ROLE',
};
export const StorageConstants = {
  PAYMENT_DETAILS:'paymentDetails',
  OFFLINE_ADDITIOAL_DISCOUNT:'offlineAdditionalDiscount',
  OFFLINE_ADDITIOAL_AMOUNT:'offlineAdditionalAmount',
  AMOUNT_COMMENTS:'amountComments',
  ACCESS_TOKEN: 'accessToken',
  REFRESH_TOKEN: 'refreshToken',
  MERCHANT_DETAILS: 'merchantDetails',
  BILLING_KEY_STATUS: 'billingKeyStatus',
  CUSTOM_CODE_MODE: 'CustomCodeMode',
  CUSTOM_CODE_TYPE: 'CustomCodeType',
  CUSTOM_CODES: 'CustomCodes',
  PRINT_MODE: 'CompleteConstant',
  DEVICE_UNIQUE_ID: 'deviceUniqueId',
  SELETED_BLE_PRINTER: 'SELETED_BLE',
  SELETED_USB_PRINTER: 'SELETED_USB',
  SELETED_LAN_PRINTER: 'SELETED_LAN',
  SELETED_KOT_BLE_PRINTER: 'SELETED_KOT_BLE',
  SELETED_KOT_USB_PRINTER: 'SELETED_KOT_USB',
  SELETED_KOT_LAN_PRINTER: 'SELETED_KOT_LAN',
  USB_PRINTER_LIST: 'USB_PRINTER_LIST',
  BLE_PRINTER_LIST: 'BLE_PRINTER_LIST',
  ALL_PRODUCTS: 'allProducts',
  ORDER_TYPES: 'orderTypes',
  IS_LOGGED_IN_FIRST_TIME: 'isLoggedInFirstTime',
  PAYMENT_MODE: 'paymentMode',
  IS_ESTIMATE_WITH_NO_ITEMS: 'IsEstimateWithNoItems',
  OFFLINE: 'offline',
  ORDER_LIST: 'orderList',
  PREVIEW_ID: 'previewId',
  PRINT_INFORMATION: 'PRINT_INFORMATION',
  OFFLINE_HOLD_ON_LIST: 'offlineHoldOnList',
  SELECTED_STORE_AND_TERMINAL: 'selectedStoreAndTerminal',
  ORDER_RESET_TIME: 'orderResetTime',
  SELECTED_DATES: 'selected_dates',
  SELECTED_DELIVERY_DATES: 'selected_delivery_dates',
  STORES_FULL_DETAILS: 'storesFullDetails',
  SELECTED_CSV_COLUMNS: 'selected_csv_columns',
  SELECT_DATE: 'select_date',
  AUTO_ADD_TO_STOCKS: 'AUTO_ADD_TO_STOCKS',
  ORDER_TYPE: 'order_type',
  IS_PUBLISH_FD: 'IS_PUBLISH_FD',
};
