export const SuccessConstants = {
  STATUS_CHANGED: 'Product status changed',
   PAYMENT_MODE_SAVED_SUCCESSFULLY:'Payment modes saved successfully!',
  PAYMENT_MODE_ADDED_SUCCESSFULLY:'Payment mode added successfully!',
  SAVE_SUCCESSFUL: 'Saved successfully',
  SENT_SUCCESSFUL: 'Sent successfully',
  CREATED_SUCCESSFUL: 'Created successfully',
  SESSION_SUCCESSFUL: 'Session Updated Successfully',
  TURN_OFF: 'Integration turned off',
  TURN_ON: 'Integration turned on',
  UPDATED_SUCCESSFULLY: 'Updated successfully',
  ADD_SUCCESSFUL: 'Added successfully',
  EDIT_SUCCESSFUL: 'Edited successfully',
  NUMBER_ADDED: 'Number added successfully!',
  ACCESS_GRANTED: 'Access granted',
  STAFF_ADDED: 'New Staff created successfully',
  TERMINAL_CREATED: 'New terminal created successfully',
  STORE_CREATED: 'New Store created successfully',
  MANAGER_ACCESS_CREATED: 'Manager access granted',
  SINGLE_MANAGER_ACCESS: 'Single manager access',
  ROLES_CHANGED_STAFF_TO_MANAGER: 'Role upgraded to manager successfully',
  DELETED_SUCCESSFUL: 'Deleted successfully',
  PASSWORD_UPDATED: 'Password updated successfully',
  ACCESS_REMOVED: 'Removed access successfully',
  LOGOUT: 'Logout successful',
  LOGIN: 'Login successful',
  COPIED: 'Copied',
  REGISTER: 'Register successfully',
  ADDON_UPDATED: 'Addon updated',
  ADDON_ADDED: 'Addon added',
  PRODUCT_UPDATED: 'Product updated',
  PRODUCT_ADDED: 'Product added',
  STOCK_UPDATED: 'Stock updated',
  STOCK_MONITOR_IS_TURNED_OFF: 'Stock monitor is turned off',
  EXPENSE_ADDED: 'Expense added',
  EXPENSE_UPDATED: 'Expense updated',
  ORDER_TYPE_TEXT: 'Order type changed successfully',
  COPY_CLIPBOARD: 'Copied to clipboard',
  PAYMENT_IS_SUCCESSFUL: 'Payment is successful',
  REFUND_PAYMENT_IS_SUCCESSFUL: 'Refund payment is successful',
  HOLD_ADDED_SUCCESSFUL: 'Hold added successfully',
  HOLD_REMOVED_SUCCESSFUL: 'Hold removed successfully',
  FETCH_SUCCESSFULLY: 'Fetch successfully',
  ADDED_VENDOR_SUCCESSFULLY: 'Added vendor successfully',
  EDITED_VENDOR_SUCCESSFULLY: 'Edited vendor successfully',
  ADDED_PURCHASE_ORDER_SUCCESSFULLY: 'Added order successfully',
  PURCHASE_ORDER_DELETED_SUCCESSFULLY: 'Purchase order deleted successfully',
  PURCHASE_ORDER_PAYMENT_IS_SUCCESSFULLY: 'Purchase Order Payment Is Successfully',
  MANAGER_ACCOUNT_IS_CREATED_SUCCESSFULLY: 'Manager account is created successfully',
  MANAGER_ACCOUNT_ACCESS_IS_CHANGED_SUCCESSFULLY: 'Manager account access is changed successfully',
  REMOVED_MANAGER_ACCOUNT_SUCCESSFULLY: 'Removed manager account successfully',
  INTEGRATION_DELETE: 'Integration Deleted Successfully',
  COUPON_APPLIED_SUCCESS: 'Coupon applied successfully!',
};
